### ISSUE TITLE
Android aab's are not correctly signed

### ISSUE THREAD

**Issue by goldeneagle66** [Danielku15/SigningServer#36]
An aab can be signed by renaming it to *.jar, but it will only be signed with SHA1 even though the configuration file contains "HashAlgorithm": "SHA256".

This can be verified by using 
jarsigner -verify some.jar -verbose

output:

    Digest algorithm: SHA1 (disabled)
    Signature algorithm: SHA1withRSA (disabled), 2048-bit key

WARNING: The jar will be treated as unsigned, because it is signed with a weak algorithm that is now disabled by the security property:

jdk.jar.disabledAlgorithms=MD2, MD5, RSA keySize < 1024, DSA keySize < 1024, SHA1 denyAfter 2019-01-01, include jdk.disabled.namedCurves

**Comment by Danielku15** [comment]
@goldeneagle66  Thanks for reporting this problem. 

I did some analysis on how `apksigner` and `jarsigner` behave accordig to their documentation and source code level implementation. Based on this I can confirm that there is a different behavior in SigningServer than expected. 

I collected all information and documented it here: https://github.com/Danielku15/SigningServer/blob/dfaa274461937a27fd63c40495307823027a30ad/Docs/jarsigner-and-apksigner.md

In this document you can also find the conclusion on how the signing server will handle in future (after the fix) the signing of the different formats. 


Concretely on your bug report following points are important: 

* `.aab` files are treated as simple JARs. No special "Android" signing exists for them. Also even 
`apksigner` cannot sign AAB files properly unless you tweak various settings to make it work. 
* There is a misbehavior in the Signing Server that the requested HashAlgorithm of the client is not respected. This is caused by the fact that we use `apksigner` internal functionality for signing both APKs and JARs. But `apksigner` does not have any options normally to controll the hash algorithm. That's why signing server misbehaves.

**Comment by Danielku15** [comment]
Changes are implemented and available in the latest pre-release builds: https://github.com/Danielku15/SigningServer/actions/runs/6709066035

Server needs to be updated. Client doesn't need to be updated (but it's always encouraged).
